import './globals.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
// import Navbar from './Components/Navbar'
import LoginNavbar from './Components/Loginavbar'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Secure Stamp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        {/* <Navbar /> */}
        <LoginNavbar/>
        {children}
      </body>
    </html>
  )
}
